name: Update Confluence Pages

on:
  push:
    branches:
      - main

jobs:
  update-pages:
    runs-on: ubuntu-latest
    environment: docs-env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Versions
        run: ./bin/markfluence-linux-amd64 --version

      - name: Update pages
        env:
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}
        run: ./bin/update_pages.sh
